export const actionTypes = {

  MAIN_NAV_START_FETCHING: 'MAIN_NAV_START_FETCHING',
  MAIN_NAV_FETCHED: 'MAIN_NAV_FETCHED',
  MAIN_NAV_FETCH_ERROR: 'MAIN_NAV_FETCH_ERROR',

  MULTIPLE_CHOICE_START_FETCHING: 'MULTIPLE_CHOICE_START_FETCHING',
  MULTIPLE_CHOICE_FETCHED: 'MULTIPLE_CHOICE_FETCHED',
  MULTIPLE_CHOICE_FETCH_ERROR: 'MULTIPLE_CHOICE_FETCH_ERROR',

}